name: testandrelease

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Run gofmt
        run: |
          gofmt -s -l . | grep -v vendor

      - name: Run golint
        run: |
          go get -u golang.org/x/lint/golint && \
          $GOROOT/bin/golint ./... | grep -v vendor

      - name: Run go test
        run: |
          go test test -v $(go list ./... | grep -v vendor)

      - name: Run staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/... && \
          $GOROOT/bin/staticcheck $(shell go list ./... | grep -v vendor)

      - name: Run go vet
        run: |
          go vet $(go list ./... | grep -v vendor)

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
